version: "2.1"
services:
  web:
    build: .
    command: nodemon --inspect=0.0.0.0:9229 app.js
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
      - "9229:9229"